// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';

    // show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_PsniBAOnrwNmy5rYfegAOdwcGTHw24',
    appId: '1:551873773250:web:b05fa31881a2af6e88455b',
    messagingSenderId: '551873773250',
    projectId: 'aplikasi-belajar-cc0ef',
    authDomain: 'aplikasi-belajar-cc0ef.firebaseapp.com',
    storageBucket: 'aplikasi-belajar-cc0ef.firebasestorage.app',
    measurementId: 'G-K5V5W75S7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-m4KWiPNFJzfV0nSu6O5i3JMp_F7KltI',
    appId: '1:551873773250:android:1f907709ae6372bb88455b',
    messagingSenderId: '551873773250',
    projectId: 'aplikasi-belajar-cc0ef',
    storageBucket: 'aplikasi-belajar-cc0ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_GTn18clrNp9GKkgbO6_xymcufk-HfA',
    appId: '1:551873773250:ios:a1969f823019704188455b',
    messagingSenderId: '551873773250',
    projectId: 'aplikasi-belajar-cc0ef',
    storageBucket: 'aplikasi-belajar-cc0ef.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  
}
